version: 0.0
os: linux
files:
  - source: dist/my-angular-app
    destination: /usr/share/nginx/html
hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root